language: php
sudo: false
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer global require hirak/prestissimo

install: 
  - travis_retry travis_wait composer update --no-interaction --prefer-dist --prefer-stable

script:
  - vendor/bin/phpunit -v

jobs:
  include:
    - stage: Test
      php: 7.1
      name: prefer-lowest
      install:
        - composer remove --dev friendsofphp/php-cs-fixer phpstan/phpstan --no-update
        - travis_retry travis_wait composer install --no-interaction --prefer-dist
        - travis_retry travis_wait composer update --no-interaction --prefer-dist --prefer-stable --prefer-lowest
    - name: sentry/sentry dev-develop
      install: composer require sentry/sentry:dev-develop
    - stage: Code style and static analysis
      script:
        - composer phpstan
      env: PHPSTAN=true
    - script: 
        - composer cs-check
      env: CS-FIXER=true
    - stage: coverage
      script: 
        - phpdbg -qrr vendor/bin/phpunit --coverage-clover clover.xml
      after_success:
        - vendor/bin/ocular code-coverage:upload --format=php-clover clover.xml --revision=$TRAVIS_COMMIT
