language: php
sudo: false
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - if [[ $TRAVIS_PHP_VERSION = '7.2' ]]; then composer remove --dev friendsofphp/php-cs-fixer --no-update --no-interaction; fi

install: travis_retry composer update --no-interaction --prefer-dist --prefer-stable $COMPOSER_OPTIONS

script:
  - vendor/bin/phpunit -v

jobs:
  include:
    - stage: test
      php: 5.6
      env: COMPOSER_OPTIONS="--prefer-lowest"
    - stage: Test
      php: 7.0
      env: COMPOSER_OPTIONS="--prefer-lowest"
    - stage: codestyle
      php: 7.1
      script: 
        - vendor/bin/php-cs-fixer fix --verbose --diff --dry-run
    - stage: coverage
      php: 7.1
      script: 
        - phpdbg -qrr vendor/bin/phpunit --coverage-clover clover.xml
      after_success:
        - vendor/bin/ocular code-coverage:upload --format=php-clover clover.xml --revision=$TRAVIS_COMMIT
