language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - if [[ $TRAVIS_PHP_VERSION = '7.2' ]]; then composer remove friendsofphp/php-cs-fixer --no-install --no-interaction; fi
  - if [[ $TEST_COVERAGE ]]; then PHPUNIT_FLAGS="--coverage-clover clover.xml"; fi

install: travis_retry composer update --no-interaction --prefer-dist --prefer-stable $COMPOSER_OPTIONS

script:
  - vendor/bin/phpunit -v $PHPUNIT_FLAGS

jobs:
  include:
    - stage: Test
      php: 5.6
      env: COMPOSER_OPTIONS="--prefer-lowest"
    - stage: Test
      php: 7.0
      env: COMPOSER_OPTIONS="--prefer-lowest"

    - stage: Code style check
      php: 7.1
      script: 
        - vendor/bin/php-cs-fixer fix --verbose --diff --dry-run

    - stage: Test coverage
      php: 7.1
      script: 
        - phpdbg -qrr vendor/bin/phpunit --coverage-clover clover.xml
      after_success:
        - vendor/bin/ocular code-coverage:upload --format=php-clover clover.xml --revision=$TRAVIS_COMMIT
