language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  include:
    - php: 5.6
      env: COMPOSER_OPTIONS="--prefer-lowest"
    - php: 7.0
      env: COMPOSER_OPTIONS="--prefer-lowest"
    - php: 7.1
      env: TEST_COVERAGE=true
  allow_failures:
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - if [[ $TEST_COVERAGE ]]; then PHPUNIT_FLAGS="--coverage-clover clover.xml"; fi

install: travis_retry composer update --no-interaction --prefer-dist --prefer-stable $COMPOSER_OPTIONS

script:
  - vendor/bin/phpunit -v $PHPUNIT_FLAGS
  - vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run

after_success:
  - if [[ $TEST_COVERAGE ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi
