services:
    sentry.client:
        class: '%sentry.client%'
        arguments: ['%sentry.dsn%']
        calls:
            - [setRelease, ['%sentry.release%']]
            - [setEnvironment, ['%sentry.environment%']]
            - [setAppPath, ['%sentry.app_path%']]
            - [setPrefixes, ['%sentry.prefixes%']]

    sentry.exception_listener:
        class: '%sentry.exception_listener%'
        arguments: ['@sentry.client']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
